name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-ios:
    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: latest-stable
      - name: Set variables
        run: |
         HASH=$(cat SNAPSHOT_HASH)
         echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Just Test
        run: |
          touch Flutter
          echo $SNAPSHOT_HASH
          git tag ios-v2-${{env.SNAPSHOT_HASH}}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ios-v2-${{env.SNAPSHOT_HASH}}
          token: ${{ secrets.WORKFLOW }}
          files: |
            ./Flutter
