name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-v1:
    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: 13.4.1
      - name: Set variables
        run: |
          HASH=$(cat SNAPSHOT_HASH)
          echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Install tools
        run: |
          brew update
          brew install wget
      - name: Download Files
        run: |
          ROOT_DIR=`pwd`
          wget https://github.com/Impact-I/reFlutter/releases/download/ios-v2-${{env.SNAPSHOT_HASH}}/Flutter -O Flutter
          wget https://github.com/Impact-I/reFlutter/releases/download/android-v2-${{env.SNAPSHOT_HASH}}/libflutter_arm.so -O libflutter_arm.so
          wget https://github.com/Impact-I/reFlutter/releases/download/android-v2-${{env.SNAPSHOT_HASH}}/libflutter_arm64.so -O libflutter_arm64.so
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #target_commitish: v1-${{env.SNAPSHOT_HASH}}
          tag_name: v1-${{env.SNAPSHOT_HASH}}
          token: ${{ secrets.WORKFLOW }}
          files: |
            ./Flutter
            ./*.so

  build-v2:
    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: 13.4.1
      - name: Set variables
        run: |
          HASH=$(cat SNAPSHOT_HASH)
          echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Install tools
        run: |
          brew update
          brew install wget
      - name: Download Files
        run: |
          ROOT_DIR=`pwd`
          wget https://github.com/Impact-I/reFlutter/releases/download/ios-v3-${{env.SNAPSHOT_HASH}}/Flutter -O Flutter
          wget https://github.com/Impact-I/reFlutter/releases/download/android-v3-${{env.SNAPSHOT_HASH}}/libflutter_arm.so -O libflutter_arm.so
          wget https://github.com/Impact-I/reFlutter/releases/download/android-v3-${{env.SNAPSHOT_HASH}}/libflutter_arm64.so -O libflutter_arm64.so
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #target_commitish: v2-${{env.SNAPSHOT_HASH}}
          tag_name: v2-${{env.SNAPSHOT_HASH}}
          token: ${{ secrets.WORKFLOW }}
          files: |
            ./Flutter
            ./*.so
